import type { IconType } from 'react-icons';
import {
  FaBrain,
  FaChartLine,
  FaCode,
  FaEnvelope,
  FaEye,
  FaGithub,
  FaLanguage,
  FaLayerGroup,
  FaLinkedin,
  FaProjectDiagram,
  FaRobot,
  FaSearch,
} from 'react-icons/fa';
import {
  SiC,
  SiDocker,
  SiExpress,
  SiFastapi,
  SiGit,
  SiGithub,
  SiHtml5,
  SiHuggingface,
  SiJavascript,
  SiJsonwebtokens,
  SiJupyter,
  SiLinux,
  SiMongodb,
  SiMysql,
  SiNodedotjs,
  SiNumpy,
  SiOpencv,
  SiOpenjdk,
  SiPandas,
  SiPlotly,
  SiPython,
  SiPytorch,
  SiReact,
  SiRender,
  SiScikitlearn,
  SiStreamlit,
  SiSwagger,
  SiTailwindcss,
  SiTensorflow,
  SiVercel,
} from 'react-icons/si';
import { VscVscode } from 'react-icons/vsc';

const ICONS: Record<string, IconType> = {
  FaBrain,
  FaChartLine,
  FaCode,
  FaEnvelope,
  FaEye,
  FaGithub,
  FaLanguage,
  FaLayerGroup,
  FaLinkedin,
  FaProjectDiagram,
  FaRobot,
  FaSearch,
  SiC,
  SiDocker,
  SiExpress,
  SiFastapi,
  SiGit,
  SiGithub,
  SiHtml5,
  SiHuggingface,
  SiJavascript,
  SiJsonwebtokens,
  SiJupyter,
  SiLinux,
  SiMongodb,
  SiMysql,
  SiNodedotjs,
  SiNumpy,
  SiOpencv,
  SiOpenjdk,
  SiPandas,
  SiPlotly,
  SiPython,
  SiPytorch,
  SiReact,
  SiRender,
  SiScikitlearn,
  SiStreamlit,
  SiSwagger,
  SiTailwindcss,
  SiTensorflow,
  SiVercel,
  VscVscode,
};

export default function Icon({ name, className }: { name: string; className?: string }) {
  const Component = ICONS[name];
  if (!Component) return null;
  return <Component className={className} aria-hidden="true" />;
}
